spring:
  application:
    name: medical-consultation

  config:
    import:
      - optional:configserver:http://config-server:8888/database.yml
      - optional:configserver:http://config-server:8888/keycloak.yml
      - optional:configserver:http://config-server:8888/eureka-server.yml
      - optional:configserver:http://config-server:8888/jwt-converter.yml

server:
  port: 8084
